In [1]:
import numpy as np
import pandas as pd
import statistics
import os

In [2]:
wheel=np.array([0,32,15,19,4,21,2,25,17,34,6,27,13,36,11,30,8,23,10,5,24,16,33,1,20,14,31,9,22,18,29,7,28,12,35,3,26])

In [348]:
os.chdir(r"C:\Users\sudhe\Desktop\GitHub Repository\Roulette-Spyder")
master_spin_data=pd.read_csv('master_spin_data.csv')

In [3]:
spin_wheel_1st_numbers=wheel[1::3]
spin_wheel_2nd_numbers=wheel[2::3]
spin_wheel_3rd_numbers=wheel[3::3]
spin_wheel_1st_dozen=wheel[1:13]
spin_wheel_2nd_dozen=wheel[13:25]
spin_wheel_3rd_dozen=wheel[25:37]
first_dozen=np.arange(1,13)
second_dozen=np.arange(13,25)
third_dozen=np.arange(25,37)
first_row=np.arange(1,37,3)
second_row=np.arange(2,37,3)
third_row=np.arange(3,37,3)
tiers=np.array([27,13,36,11,30,8,23,10,5,24,16,33])
orphelins=np.array([17,34,6,1,20,14,31,9])
jeu_zero_voisins=np.array([0,32,15,19,4,21,2,25,22,18,29,7,28,12,35,3,26])

In [5]:
first_dozen_first_row_11=np.union1d(first_dozen,first_row)
first_dozen_second_row_12=np.union1d(first_dozen,second_row)
first_dozen_third_row_13=np.union1d(first_dozen,third_row)
second_dozen_first_row_21=np.union1d(second_dozen,first_row)
second_dozen_second_row_22=np.union1d(second_dozen,second_row)
second_dozen_third_row_23=np.union1d(second_dozen,third_row)
third_dozen_first_row_31=np.union1d(third_dozen,first_row)
third_dozen_second_row_32=np.union1d(third_dozen,second_row)
third_dozen_third_row_33=np.union1d(third_dozen,third_row)

In [177]:
new_dozen1=wheel[1:].reshape(18,2)[::3].flatten()
new_dozen2=wheel[1:].reshape(18,2)[1::3].flatten()
new_dozen3=wheel[1:].reshape(18,2)[2::3].flatten()

In [180]:
previous_landing=master_spin_data.iloc[720].spin_landing
count=1
landing_count=[]
#temp=np.union1d(first_dozen,third_dozen)
temp=new_dozen3
for i in master_spin_data.iloc[721:].spin_landing.values:
    if pd.Series(temp).isin([i]).sum()==1 and pd.Series(temp).isin([previous_landing]).sum()==1:
        count+=1
    else:
        landing_count.append(count)
        count=1
        
    previous_landing=i

pd.Series(landing_count).value_counts()
#np.array(pd.Series(landing_count))

1    466
2     18
4      5
3      3
5      2
6      1
dtype: int64

In [140]:
spin_wheel_1st_numbers

array([32,  4, 25,  6, 36,  8,  5, 33, 14, 22,  7, 35])

In [142]:
wheel[::3]

array([ 0, 19,  2, 34, 13, 30, 10, 16, 20,  9, 29, 12, 26])

In [ ]:
1,2,3,4,6,12

In [146]:
wheel[1:].reshape(3,12)

array([[32, 15, 19,  4, 21,  2, 25, 17, 34,  6, 27, 13],
       [36, 11, 30,  8, 23, 10,  5, 24, 16, 33,  1, 20],
       [14, 31,  9, 22, 18, 29,  7, 28, 12, 35,  3, 26]])

In [148]:
wheel[1:].reshape(4,9)

array([[32, 15, 19,  4, 21,  2, 25, 17, 34],
       [ 6, 27, 13, 36, 11, 30,  8, 23, 10],
       [ 5, 24, 16, 33,  1, 20, 14, 31,  9],
       [22, 18, 29,  7, 28, 12, 35,  3, 26]])

In [158]:
np.concatenate((wheel[1:],wheel[0]),axis = None)

array([32, 15, 19,  4, 21,  2, 25, 17, 34,  6, 27, 13, 36, 11, 30,  8, 23,
       10,  5, 24, 16, 33,  1, 20, 14, 31,  9, 22, 18, 29,  7, 28, 12, 35,
        3, 26,  0])

In [167]:
np.concatenate((wheel[2:],wheel[:1]),axis = None)

array([15, 19,  4, 21,  2, 25, 17, 34,  6, 27, 13, 36, 11, 30,  8, 23, 10,
        5, 24, 16, 33,  1, 20, 14, 31,  9, 22, 18, 29,  7, 28, 12, 35,  3,
       26,  0])

In [ ]:
for i in wheel[1:].reshape(18,2):
    

In [163]:
wheel[1:].reshape(18,2)[::3].flatten()

array([32, 15, 25, 17, 36, 11,  5, 24, 14, 31,  7, 28])

In [164]:
wheel[1:].reshape(18,2)[1::3].flatten()

array([19,  4, 34,  6, 30,  8, 16, 33,  9, 22, 12, 35])

In [165]:
wheel[1:].reshape(18,2)[2::3].flatten()

array([21,  2, 27, 13, 23, 10,  1, 20, 18, 29,  3, 26])

In [166]:
wheel[1:].reshape(12,3)[::3].flatten()

array([32, 15, 19,  6, 27, 13,  5, 24, 16, 22, 18, 29])

In [173]:
np.concatenate((wheel[3:],wheel[:3]),axis = None)

array([19,  4, 21,  2, 25, 17, 34,  6, 27, 13, 36, 11, 30,  8, 23, 10,  5,
       24, 16, 33,  1, 20, 14, 31,  9, 22, 18, 29,  7, 28, 12, 35,  3, 26,
        0, 32, 15])

In [196]:
np.concatenate((wheel[36:],wheel[:36]),axis = None)

array([26,  0, 32, 15, 19,  4, 21,  2, 25, 17, 34,  6, 27, 13, 36, 11, 30,
        8, 23, 10,  5, 24, 16, 33,  1, 20, 14, 31,  9, 22, 18, 29,  7, 28,
       12, 35,  3])

In [199]:
np.arange(1,37).reshape(-1,2,3).tolist()

[[[1, 2, 3], [4, 5, 6]],
 [[7, 8, 9], [10, 11, 12]],
 [[13, 14, 15], [16, 17, 18]],
 [[19, 20, 21], [22, 23, 24]],
 [[25, 26, 27], [28, 29, 30]],
 [[31, 32, 33], [34, 35, 36]]]

In [ ]:
np.tolist()

In [363]:
from itertools import combinations 
comb = combinations(np.arange(1,37).reshape(-1,2,3).tolist(),2) 

dozens=[]
dict_universal={i:0 for i in range(1,50)}
sum_of_total_dozen_bets=pd.Series(dict_universal)
for i in list(comb):
    dozens.append(np.array(list(i)).flatten().tolist())

for dozen in dozens:
    previous_landing=master_spin_data.iloc[2016].spin_landing
    count=1
    landing_count=[]
    
    #temp=np.setdiff1d(np.arange(1,37),np.array(dozen))
    temp=dozen
    for i in master_spin_data.iloc[2017:].spin_landing.values:
        if pd.Series(temp).isin([i]).sum()==1 and pd.Series(temp).isin([previous_landing]).sum()==1:
            count+=1
        else:
            landing_count.append(count)
            count=1

        previous_landing=i
    
    sum_of_total_dozen_bets=sum_of_total_dozen_bets.add(pd.Series(landing_count).value_counts(),fill_value=0).fillna(0)
    
    print("Dozen {}       : {}".format(dozen,pd.Series(landing_count).max()))
    print(pd.Series(landing_count).value_counts().to_dict())

sum_of_total_dozen_bets=sum_of_total_dozen_bets[sum_of_total_dozen_bets!=0.0]
print(sum_of_total_dozen_bets)

'''
bid_muitiplier=[2,3,5,5]
for i in range (5,20):
    print(i,sum_of_total_dozen_bets[sum_of_total_dozen_bets.index>i][:4].reset_index(drop=True).mul(pd.Series(bid_muitiplier)).sum()-sum_of_total_dozen_bets[sum_of_total_dozen_bets.index>i][4:].sum()*13)

'''


Dozen [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]       : 5
{1: 468, 2: 19, 3: 9, 4: 2, 5: 1}
Dozen [1, 2, 3, 4, 5, 6, 13, 14, 15, 16, 17, 18]       : 6
{1: 447, 2: 27, 3: 7, 6: 2, 4: 2, 5: 1}
Dozen [1, 2, 3, 4, 5, 6, 19, 20, 21, 22, 23, 24]       : 4
{1: 461, 2: 23, 3: 8, 4: 4}
Dozen [1, 2, 3, 4, 5, 6, 25, 26, 27, 28, 29, 30]       : 4
{1: 468, 2: 22, 3: 9, 4: 2}
Dozen [1, 2, 3, 4, 5, 6, 31, 32, 33, 34, 35, 36]       : 4
{1: 490, 2: 13, 3: 9, 4: 1}
Dozen [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]       : 5
{1: 440, 2: 28, 3: 11, 4: 3, 5: 1}
Dozen [7, 8, 9, 10, 11, 12, 19, 20, 21, 22, 23, 24]       : 4
{1: 435, 2: 32, 3: 13, 4: 2}
Dozen [7, 8, 9, 10, 11, 12, 25, 26, 27, 28, 29, 30]       : 6
{1: 420, 2: 30, 4: 8, 3: 7, 6: 1, 5: 1}
Dozen [7, 8, 9, 10, 11, 12, 31, 32, 33, 34, 35, 36]       : 6
{1: 460, 2: 25, 3: 7, 6: 1, 5: 1, 4: 1}
Dozen [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]       : 6
{1: 428, 2: 33, 3: 7, 4: 4, 5: 2, 6: 1}
Dozen [13, 14, 15, 16, 17, 18, 25, 26, 27, 28, 29, 30

'\nbid_muitiplier=[2,3,5,5]\nfor i in range (5,20):\n    print(i,sum_of_total_dozen_bets[sum_of_total_dozen_bets.index>i][:4].reset_index(drop=True).mul(pd.Series(bid_muitiplier)).sum()-sum_of_total_dozen_bets[sum_of_total_dozen_bets.index>i][4:].sum()*13)\n\n'

In [277]:
bid_muitiplier=[2,3,5,5]
for i in range (5,20):
    print(i,sum_of_total_dozen_bets[sum_of_total_dozen_bets.index>i][:4].reset_index(drop=True).mul(pd.Series(bid_muitiplier)).sum()-sum_of_total_dozen_bets[sum_of_total_dozen_bets.index>i][4:].sum()*13)

sum_of_total_dozen_bets

5 85.0
6 70.0
7 1.0
8 13.0
9 -7.0
10 1.0
11 -2.0
12 21.0
13 21.0
14 23.0
15 14.0
16 5.0
17 2.0
18 0.0
19 0.0


1     4601.0
2      541.0
3      333.0
4      251.0
5      150.0
6       96.0
7       69.0
8       39.0
9       36.0
10      18.0
11      10.0
12       9.0
13       5.0
14       4.0
15       2.0
16       3.0
17       1.0
18       1.0
dtype: float64

In [367]:
dict_universal={i:0 for i in range(1,50)}
sum_of_gun_theory_bets=pd.Series(dict_universal)
for dozen in dozens:
    for row in [first_row,second_row,third_row]:
        temp=np.union1d(np.array(dozen),row)
        previous_landing=master_spin_data.iloc[0].spin_landing
        count=1
        landing_count=[]

        for i in master_spin_data.iloc[1:].spin_landing.values:
            if pd.Series(temp).isin([i]).sum()==1 and pd.Series(temp).isin([previous_landing]).sum()==1:
                count+=1
            else:
                landing_count.append(count)
                count=1

            previous_landing=i

        sum_of_gun_theory_bets=sum_of_gun_theory_bets.add(pd.Series(landing_count).value_counts(),fill_value=0).fillna(0)

        print("{}".format(pd.Series(landing_count).max()))
        print(dozen,row)
        print(pd.Series(landing_count).value_counts().to_dict())

sum_of_gun_theory_bets=sum_of_gun_theory_bets[sum_of_gun_theory_bets!=0.0]
print(sum_of_gun_theory_bets)
        
        

        
            
        

11
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] [ 1  4  7 10 13 16 19 22 25 28 31 34]
{1: 1431, 2: 167, 3: 67, 4: 55, 5: 31, 8: 8, 7: 7, 6: 7, 9: 5, 11: 1, 10: 1}
14
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] [ 2  5  8 11 14 17 20 23 26 29 32 35]
{1: 1464, 2: 164, 3: 87, 4: 54, 5: 20, 6: 15, 8: 4, 7: 4, 9: 2, 14: 1, 10: 1}
13
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] [ 3  6  9 12 15 18 21 24 27 30 33 36]
{1: 1440, 2: 147, 3: 80, 4: 55, 5: 30, 6: 11, 7: 10, 8: 4, 9: 3, 13: 1, 10: 1}
14
[1, 2, 3, 4, 5, 6, 13, 14, 15, 16, 17, 18] [ 1  4  7 10 13 16 19 22 25 28 31 34]
{1: 1419, 2: 159, 3: 88, 4: 42, 5: 25, 6: 15, 7: 12, 8: 5, 9: 2, 14: 1, 13: 1, 10: 1}
10
[1, 2, 3, 4, 5, 6, 13, 14, 15, 16, 17, 18] [ 2  5  8 11 14 17 20 23 26 29 32 35]
{1: 1466, 2: 182, 3: 92, 4: 40, 5: 21, 6: 15, 7: 7, 8: 3, 10: 2, 9: 1}
10
[1, 2, 3, 4, 5, 6, 13, 14, 15, 16, 17, 18] [ 3  6  9 12 15 18 21 24 27 30 33 36]
{1: 1422, 2: 161, 3: 84, 4: 41, 5: 37, 6: 14, 7: 13, 8: 4, 10: 1}
10
[1, 2, 3, 4, 5, 6, 19, 20, 21, 22, 23, 24] [ 

In [368]:
9*197+10*85-24*(61+14+16+8+7+3)

7

In [316]:
master_spin_data.iloc[1366]

spin_landing                                  31
time                  2020-10-22 17:23:54.279720
session_spin_count                             1
Name: 1366, dtype: object

In [372]:
master_spin_data['spin_landing'].value_counts()

9     92
21    83
15    82
11    82
28    79
14    76
19    76
33    76
6     75
17    73
7     73
31    72
36    72
16    71
13    71
5     71
34    71
12    70
30    69
8     68
4     67
3     67
25    67
29    67
10    66
26    65
18    64
2     64
32    62
24    62
1     62
23    62
35    60
20    60
0     59
22    58
27    50
Name: spin_landing, dtype: int64

In [370]:
len(master_spin_data)

2564

spin_landing                                  31
time                  2020-10-22 17:23:54.279720
session_spin_count                             1
Name: 2016, dtype: object